baseURL = "https://pingpongclub.org"
title = "Ping Pong Club"
author = "jzhoushang"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

[params]
    
  showBlog = true
  mainSections = ["events"]

  googleFonts = true

  [params.logo]
    main = "img/logo/pingpong.png"
    alt = "Ping Pong Club Logo"
    size = "h-14"
    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/

  [params.site]
    name = "Ping Pong Club"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "The CCHS Ping Pong Club"
    meta_og_title = "Ping Pong Club"
    meta_og_type = "website"
    meta_og_url = "https://pingpongclub.org"

[menu]

  #[[menu.main]]
  #  identifier = "products"
  #  name = "Products"
  #  url = "/products/"
  #  weight = 1

  [[menu.main]]
    identifier = "register"
    name = "Register"
    url = "https://app.pingpongclub.org/"
    weight = 1
    [[menu.main.params]]
      left = false

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 2
    [[menu.main.params]]
      left = false
  
  [[menu.main]]
    identifier = "events"
    name = "Past Events"
    url = "/events/"
    weight = 3
    [[menu.main.params]]
      left = false

  [[menu.main]]
    identifier = "shop"
    name = "Shop"
    url = "https://shop.pingpongclub.org/"
    weight = 4
    [[menu.main.params]]
      left = true

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5
    [[menu.main.params]]
      left = true

  [[menu.main]]
    identifier = "club"
    name = "Club"
    url = "/club/"
    weight = 6
    [[menu.main.params]]
      left = true

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 7
    [[menu.main.params]]
      left = true

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/pingpong-club/pingpong-site"
    pre = "<i class='icon-github text-2xl'></i>"
    weight = 2

  [[menu.footer]]
    name = "Instagram"
    url = "https://instagram.com/cchs_pingpong_club"
    pre = "<i class='fa-brands fa-instagram text-2xl'></i>"
    weight = 3
